
[font]
normal = { family = "FiramonoNerdFontMedium" }

#normal = { family = "JetBrainsMono Nerd Font" }

size = 13


[window]
blur = true

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml",
]

